return {
  {
    name = "default_allow_non_manager_can_edit",
    defaultAllow = true,
    userGrant = nil,
    isManager = false,
    sameFarm = true,
    expect = { edit = true, manageGrants = false, autoComplete = true },
  },
  {
    name = "default_deny_non_manager_cannot_edit",
    defaultAllow = false,
    userGrant = nil,
    isManager = false,
    sameFarm = true,
    expect = { edit = false, manageGrants = false, autoComplete = true },
  },
  {
    name = "default_deny_but_user_grant_can_edit",
    defaultAllow = false,
    userGrant = true,
    isManager = false,
    sameFarm = true,
    expect = { edit = true, manageGrants = false, autoComplete = true },
  },
  {
    name = "default_allow_but_user_deny_cannot_edit",
    defaultAllow = true,
    userGrant = false,
    isManager = false,
    sameFarm = true,
    expect = { edit = false, manageGrants = false, autoComplete = true },
  },
  {
    name = "manager_always_edit_and_manage",
    defaultAllow = false,
    userGrant = false,
    isManager = true,
    sameFarm = true,
    expect = { edit = true, manageGrants = true, autoComplete = true },
  },
  {
    name = "other_farm_denied",
    defaultAllow = true,
    userGrant = true,
    isManager = true,
    sameFarm = false,
    expect = { edit = false, manageGrants = false, autoComplete = false },
  },
}
